---
name: Build game

on: [ push, pull_request ]

jobs:

  build-msvc:
    name: Windows build
    runs-on: windows-2019
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
      CONAN_USER_HOME_SHORT: None
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Build tools
        run: git clone https://git.anotherfoxguy.com/AnotherFoxGuy/build-tools.git %BUILD_TOOLS_PATH%
        shell: cmd

      - name: Cache conan packages
        uses: actions/cache@v4
        with:
          key: conan-windows-${{ hashFiles('conanfile.py') }}
          path: ~/.conan2

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Configure
        run: |
          conan remote add rigs-of-rods-deps https://conan.cloudsmith.io/rigs-of-rods/deps/ -f
          conan install . -b missing -pr:b=tools/conan-profiles/vs-19-release-ninja -pr=tools/conan-profiles/vs-19-release-ninja
          cmake --preset conan-release -DCMAKE_INSTALL_PREFIX=redist -DCREATE_CONTENT_FOLDER=ON
        shell: cmd

      - name: Build
        run: ninja install
        shell: cmd

      - name: Upload build to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: env.BUTLER_API_KEY != null && github.ref == 'refs/heads/master'
        run: |
          choco install butler -y
          butler push redist rigs-of-rods/rigs-of-rods-dev:windows-ci --userversion CIBuild-%GITHUB_RUN_NUMBER%-Commit-%GITHUB_SHA%
        shell: cmd

      - name: Upload redist folder
        uses: actions/upload-artifact@v4
        with:
          name: ror-win
          path: redist

      - name: Clean Conan pkgs
        run: conan cache clean "*" -sbd
        shell: cmd
